-- Generated by Oracle SQL Developer Data Modeler Version: 2.0.0 Build: 584
--   at:        2012-10-05 00:18:31
--   site:      SQL Server 2005
--   type:      SQL Server 2005
--Base de datosNegociosJavaNet


Create Database negociosjavanet
Go

Use negociosjavanet
Go

CREATE TABLE Articulo 
    (
     IdArticulo int NOT NULL identity(1,1), 
     Descripcion VARCHAR (200) , 
     Precio DECIMAL (18,6) , 
     Stock INTEGER
     CONSTRAINT Articulo_PK PRIMARY KEY(IdArticulo)
    )


CREATE TABLE Cliente 
    (
     IdCliente int NOT NULL identity(1,1),
     dni VARCHAR (8) , 
     nombres VARCHAR (60) , 
     apellidos VARCHAR (60) ,
     email VARCHAR (60) ,
     direccion  VARCHAR (200) ,
     celular VARCHAR (9) ,
     contrasena VARCHAR (20) , 
     estado INTEGER 
     CONSTRAINT Cliente_PK PRIMARY KEY (IdCliente)
    )
GO 

Insert into cliente  values('43873938','Jeanpierre','Cajo Hernandez','jcajo@gmail.com','Las rosas 175','999999999','123','1')
Insert into cliente  values('42178733','Ronald','Tapia','liontapia@hotmail.com','Av. Fresnos 576 Urb. Gardenias','999999999','123','1')
Insert into cliente  values('40136711','Raul', 'Alva','ralva@gmail.com','Las golondrinas 278','999999999','123','1')
Insert into cliente  values('20202020','Daniel','Zelaya','dzelaya@gmail.com','av. maldonado 2345','999999999','123','1')
Insert into cliente  values('30303030','Ronald','Gates','rgates@gmail.com','av. rosa toro 897','999999999','123','1')

CREATE TABLE Pedido 
    (
     IdPedido int NOT NULL identity(1,1), 
     Fecha DATETIME , 
     CondPago VARCHAR (20) , 
     TipMon VARCHAR (10) , 
     TipCam DECIMAL (18,6) , 
     SubTotal DECIMAL (18,6) , 
     Total DECIMAL (18,6) , 
     IdCliente int
     CONSTRAINT Pedido_PK PRIMARY KEY (IdPedido)
    )
GO 
    
CREATE TABLE DetallePedido 
    (
     IdPedido int, 
     ItemPedido VARCHAR (10) NOT NULL , 
     Precio DECIMAL (18,6) , 
     Cantidad INTEGER , 
     IdArticulo int 
     CONSTRAINT DetallePedido_PK PRIMARY KEY  (ItemPedido)
    )
GO 

ALTER TABLE Pedido 
    ADD CONSTRAINT Relation_1 FOREIGN KEY (IdCliente) REFERENCES Cliente (IdCliente) 
GO 

ALTER TABLE DetallePedido 
    ADD CONSTRAINT Relation_2 FOREIGN KEY (IdPedido) REFERENCES Pedido (IdPedido)
GO 

ALTER TABLE DetallePedido 
    ADD CONSTRAINT Relation_3 FOREIGN KEY (IdArticulo) REFERENCES Articulo (IdArticulo)
GO


drop table productopendiente;
GO
create table productopendiente
	(
	 id_reg int identity(1,1),
	 codproducto varchar(20),
	 descripcion varchar(20),
	 cantidad int
	)
GO
insert into productopendiente values('P0001','Televisor',2)
insert into productopendiente values('P0002','Radio',2)
select id_reg,codproducto,descripcion,cantidad from productopendiente
    
/*

--base de datos BDRiesgo
CREATE TABLE Deuda 
    (
     Iddeuda INTEGER NOT NULL , 
     DNI VARCHAR (20) NOT NULL , 
     Total DECIMAL (18,6) , 
     CONSTRAINT Deuda_PK PRIMARY KEY (Iddeuda)
    )
GO 
    
--base datos Reniec


CREATE TABLE Persona 
    (
     Dni VARCHAR (15) NOT NULL , 
     Nombres VARCHAR (50) NOT NULL , 
     Apellidos VARCHAR (250) NOT NULL , 
     Direccion VARCHAR (100) , 
     Estado BIT , 
     CONSTRAINT Persona_PK PRIMARY KEY  (Dni)
    )
GO 

--base datos BDProveedor
CREATE TABLE Producto 
    (
     id_producto VARCHAR (20) NOT NULL , 
     Descripcion VARCHAR (250) NOT NULL , 
     Precio DECIMAL (18,6) NOT NULL , 
     Stock INTEGER , 
     CONSTRAINT Producto_PK PRIMARY KEY  (id_producto)
    )
GO 

*/
